# Generated by Django 4.2.15 on 2024-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocEmp', models.CharField(max_length=100)),
                ('TipoDocEmp', models.CharField(max_length=50)),
                ('MunicipioEmp', models.CharField(max_length=100)),
                ('VisionComercial2', models.TextField()),
                ('empleados', models.IntegerField()),
                ('SeccionEconomicaEmp', models.CharField(max_length=100)),
                ('GrupoDeAtencion', models.CharField(max_length=100)),
                ('Sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoSAP', models.CharField(max_length=50)),
                ('Contenido', models.TextField()),
                ('producto', models.CharField(max_length=100)),
                ('Minimo', models.IntegerField()),
                ('Maximo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('DocEmp', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('pedidos', models.IntegerField()),
            ],
        ),
    ]
